### ISSUE TITLE
トランザクションを適切に処理するためにRollBackを追加する

### ISSUE THREAD

**Issue by yusei53** [Peach-Tech0927/product-list-backend#6]
https://divide-and-conquer.blog/go/go%E3%81%A7%E3%83%88%E3%83%A9%E3%83%B3%E3%82%B6%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E5%87%A6%E7%90%86%E3%82%92%E3%82%84%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B/

↑参考記事

**Comment by rukalice** [comment]
defer tx.Rollback()
